#!/usr/bin/env node
"use strict";
/* 
  Pretty print JSON from the standard input
  or a file

  Usage: command outputting json | jsonpp OR
         jsonpp <file>


  Bug: node 0.8 can't read from stdin
*/
var file = process.argv[2];
if(file) {
  (function() {
    var fs = require("fs");
    var fileContents = fs.readFileSync(file);
    var object = JSON.parse(fileContents);
    var pretty = JSON.stringify(object, null, 2);
    console.log(pretty);
  })();
} else {
  (function() {
    var json = "";
    process.stdin.on("data", function(chunk) {
      json += chunk;
    });
    
    process.stdin.on("end", function() {
      var object = JSON.parse(json);
      var pretty = JSON.stringify(object, null, 2);
      console.log(pretty);
    });
  })();
}
